[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"
